#!/bin/bash

if [ -d $HOME/.rbenv ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"

  ruby -v
  ruby <<< "`sed -n $(( $LINENO + 5 ))',$p' $0`"
fi

exit

# embedded ruby code
puts 'Running specs...'

require 'rspec'
flag = RSpec::Core::Runner.run(['spec'], $stderr, $stdout)

if flag != 0
  message = <<-MSG
\e[31m
---------------------------------------
Fix your changes/specs before commit!!!
---------------------------------------
\e[0m
  MSG
  puts message
end
exit flag
